version: "3"
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./customer.sql:/docker-entrypoint-initdb.d/customer.sql
    ports:
      - 5432:5432